name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Clean install dependencies
        run: npm ci
      - name: Run deploy script
        run: |
          git config user.name "David Custódio" && git config user.email "davidlacustodio@gmail.com"
          npm run gh-pages-deploy
